[package]
name = "qdd"
version = "0.1.0"
edition = "2021"

[dependencies]
nix = { version = "0.28.0", features = ["fs", "zerocopy"] }

[profile.release]
strip = true
opt-level = 3
overflow-checks = false
lto = true
codegen-units = 1
